all: insert heap merge quick

generate:
	javac GenerateStrings.java;
	java GenerateStrings;

insert:
	javac -encoding utf-8 Insert.java;
	java Insert;

heap:
	javac -encoding utf-8 Heap.java;
	java Heap;

merge:
	javac -encoding utf-8 Merge.java;
	java Merge;

quick:
	javac -encoding utf-8 Quick.java;
	java Quick;

clean:
	rm *.class
