	.ORIG  X1500
	ST R0,SAVER0
	ST R1,SAVER1
	ST R2,SAVER2
	ST R7,SAVER7
CHECK	LD R0,KBSR
	BRzp	CHECK
	LDI R0,KBDR
	LD R1,ZERO
	NOT R1,R1
	ADD R1,R1,#1
	ADD R1,R0,R1
	BRn	NOTNUM
	LD R1,NINE
	NOT R1,R1
	ADD R1,R1,#1
	ADD R1,R0,R1
	BRp	NOTNUM
	LEA R0,S1
	BRnzp	PUTSTR
NOTNUM	LEA R0,S2

PUTSTR	LDR  R1,R0,#0
	BRz	FINISH
	ADD R0,R0,#1
	JSR	PUTCHR
	BRnzp	PUTSTR

FINISH	
	LD R1,NEWLINE  
	JSR	PUTCHR
	JSR	PUTCHR
	LD R0,SAVER0
	LD R1,SAVER1
	LD R2,SAVER2
	LD R7,SAVER7
	RTI


PUTCHR  LD R2,DSR    ;put char stored in r1
	BRzp	PUTCHR  
	LD R2,DDR
	STR R1,R2,#0
	RET




KBSR	.FILL  XFE00
KBDR	.FILL  XFE02
DSR	.FILL  XFE04
DDR     .FILL  XFE06
NEWLINE .FILL  X0A
ZERO	.FILL  #48
NINE	.FILL  #57
SAVER0	.BLKW  1
SAVER1  .BLKW  1
SAVER2  .BLKW  1
SAVER7  .BLKW  1
S1	.STRINGZ	"ICS2017:It is a number."
S2	.STRINGZ	"ICS2017: ?????? What is this ??????"

	.END