	.ORIG X3000
	LD R6 , STK
	LD R0,MASK
	STI R0,KBSR
	LD R0,CDADDR
	STI R0,INTKB
	

LOOP	LEA  R0,S1
	TRAP X22
	LD R0,NEWLINE
	TRAP X21
	JSR  DELAY
	LEA R0,S2
	TRAP X22
	LD R0,NEWLINE
	TRAP X21
	JSR DELAY
	BRnzp  LOOP

DELAY   ST    R7,SAVER7
	ST    R1, SaveR1 
        LD    R1, COUNT 
REP     ADD R1,R1,#-1 
        BRp REP 
        LD    R1, SaveR1 
	LD    R7,SAVER7
	RET 
COUNT  	.FILL #2500
SaveR1	.BLKW  1
SAVER7	.BLKW  1
CDADDR  .FILL  X1500
INTKB   .FILL  X0180
KBSR	.FILL  XFE00
MASK	.FILL  X4000 
NEWLINE .FILL  X0A
STK	.FILL  X3000
S1	.STRINGZ	"CS@USTC       CS@USTC       CS@USTC       CS@USTC       CS@USTC"
S2	.STRINGZ	"       CS@USTC       CS@USTC       CS@USTC       CS@USTC"
	.END 