all: insert heap merge
	
insert:
	javac -encoding utf-8 Insert.java;
	java Insert;

heap:
	javac -encoding utf-8 Heap.java;
	java Heap;

merge:
	javac -encoding utf-8 Merge.java;
	java Merge;

clean:
	rm *.class
