all: bubble quick  counting radix
	
generate:
	javac GenerateInteger.java;
	java GenerateInteger;

bubble:
	javac -encoding utf-8 Bubble.java;
	java Bubble;

radix:
	javac -encoding utf-8 Radix.java;
	java Radix;

counting:
	javac -encoding utf-8 Counting.java;
	java Counting;

quick:
	javac -encoding utf-8 Quick.java;
	java Quick;
clean:
	rm *.class
